name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: NazariMahdi-Pro
          outputs: dist/github-snake.svg

      - name: Push Snake to output branch
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout -B output || git checkout output
          git add dist/github-snake.svg
          git commit -m "Update GitHub Snake" || echo "Nothing to commit"
          git push --force "https://${{ secrets.GH_PAT }}@github.com/NazariMahdi-Pro/NazariMahdi-Pro.git" output
